version: '2'
services:
    mysql:
        image: mysql
        volumes:
            - /docker/mysql:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123
        command: mysql -e 'CREATE DATABASE IF NOT EXISTS RAP2_DELOS_APP DEFAULT CHARSET utf8 COLLATE utf8_general_ci'
    rap2:
        # user: node
        build: .
        volumes:
            - ./:/usr/app/rap2
        ports:
            - "3030:8080"
        depends_on:
            - mysql