version: '2'
services:
    mysql:
        build: ./mysql
        volumes:
            - /docker/mysql:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123
        expose:
            - "3306"
    rap2:
        # user: node
        build: .
        # volumes:
        #     - /docker/app/rap2:/usr/app/rap2
        ports:
            - "8080:8080"
        depends_on:
            - mysql
        # command:  mysql -h localhost -u root --password='123' -e 'CREATE DATABASE IF NOT EXISTS RAP2_DELOS_APP DEFAULT CHARSET utf8 COLLATE utf8_general_ci'